function iEEG = remove_useless_ieeg_fields(iEEG)
    %%
    for isubj = iEEG.Nsubj:-1:1

        if iEEG.subjinfo(isubj).NumChannel == 1
            iEEG.subjinfo(isubj) = [];
            iEEG.Nsubj = iEEG.Nsubj - 1;
        end

    end

    iEEG.cortex.W = [];

    Nsubj = iEEG.Nsubj;
    %%
    fields_rm = [{'isubj'}, ...
        {'idx'}, ...
        {'ChannelNameOrig'}, ...
        {'ChannelName'}, ...
        {'ChannelGroup'}, ...
        {'ChannelId'}, ...
        {'ChannelNameBipolar'}, ...
        {'ChannelNameFirst'}, ...
        {'ChannelNameSecond'}, ...
        {'ChannelPositionOrig'}, ...
        {'ChannelRegionOrig'}, ...
        {'HemisphereOrig'}, ...
        {'ChannelPositionFirst'}, ...
        {'ChannelPositionSecond'}, ...
        {'ChannelNameAllOrig'}, ...
        {'idx_raworder2hmorder'}, ...
        {'idx_subj_rawch2hmch'}, ...
        {'LvjVec'}, ...
        {'LvjOrig'}, ...
        {'Lvj'}, ...
        {'Tjv'}, ...
        {'Wout'}, ...
        {'headmodelfile'}, ...
        {'ChType'}, ...
        {'ChNameFirst'}, ...
        {'ChannelIdSecond'}, ...
        {'ChNameSecond'}, ...
        {'ChNameAll'}, ...
        {'ChannelBst'}, ...
        {'LvjW'}, ...
        {'WTvj'}, ...
        {'WoutLap'}];
    iEEG.subjinfo = mv_rmfield(iEEG.subjinfo, fields_rm);

end